#pragma once
//TODO: json configs

#define MAXIMUMTHREAD 100
#define MAXIMUMTASK 10000 	//    BOOST_STATIC_ASSERT(size < 65536);
#define DIMENSION 3
#define STOPLEVEL 1
#define PRINT 0
#define CLOUDRECURSIVEPOINTCAP 10000
#define MINVOLUME 0.0005
#define ENABLE_CGAL_FILTER_CALCULATION
#define ENABLE_CGAL_SURFACE_CALCULATION
#define ADD_DEBUG

#ifdef ADD_DEBUG
	#define ENABLE_DEBUG
#endif

#ifdef ENABLE_CGAL_FILTER_CALCULATION
	#define ENABLE_CGAL_FILTER
#endif

#ifdef ENABLE_CGAL_SURFACE_CALCULATION
	#define ENABLE_CGAL_SURFACE
#endif

